AllCops:
Exclude:
  # route file is DSL
  - 'config/routes.rb'
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 5.2.4.2

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

# modern editors and terminal fit more than 80 characters.
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/models/key_values.rb'
    - 'app/models/key_values/**/**/*.rb'


# Class length is not critical to code quality
Metrics/ClassLength:
  Enabled: false

# Block length is ok to be long in DSLs like 'rspec' or 'rake'
Metrics/BlockLength:
  Enabled: false


# defualt '10 line' is too strict to us, and may clutter the class
Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

# Most Rails generated class are not doced, and not needed
Style/Documentation:
  Enabled: false

# 'return' makes code more readable in some cases
Style/RedundantReturn:
  Enabled: false

# Taiwan Greate again
Style/AsciiComments:
  Enabled: false
